[tool.ruff]
line-length = 88  # Satır uzunluğu (default: 88)
indent-width = 4  # Girinti genişliği
target-version = "py310"  # Python sürümü (3.9 örneği)

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]  # Etkinleştirilecek kurallar
ignore = []  # Yoksayılacak kurallar
fixable = ["ALL"]  # Otomatik düzeltilebilecek hatalar
